config/routes.rb
Dodream::Application.routes.draw do
  resources :pictures

  devise_for :users, controllers:{sessions:"sessions"}

  devise_scope :user do
    resources :sessions, only: [:create, :destroy]
  end

  resources :friends, only:[:create]

  resources :relationships, only: [:create, :destroy] 
  resources :angelships, only: [:create, :destroy]

  resources :token_authentications, only:[:create,:destroy]

  resources :goals do
    collection do
      get 'me'
    end
    resources :goal_posts
  end

  resources :goal_posts do
    collection do
      get 'posts'
      get 'friendsgoals'
    end
    resources :comments
  end

  root to: 'goals#index'

end

app/models/angelship.rb
class Angelship < ActiveRecord::Base
	attr_accessible :dreamer_id

	belongs_to :angel, class_name: "User"
	belongs_to :dreamer, class_name: "User"

	validates :angel_id, presence: true
	validates :dreamer_id, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
  belongs_to :goal_post
end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :user
	has_many :goal_posts
	has_many :comments, through: :goal_posts
end

app/models/goal_post.rb
class GoalPost < ActiveRecord::Base
	belongs_to :user
  belongs_to :goal
  default_scope order: 'updated_at DESC'
  has_many :comments

  has_many :pictures, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :pictures
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :image

  belongs_to :imageable, polymorphic: true
	mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	attr_accessible :followed_id

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	# goal - goal_post - comment
	has_many :goals
	has_many :goal_posts
	has_many :comments

  mount_uploader :avatar, AvatarUploader

	# user relationships
	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed
	has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
	has_many :followers, through: :reverse_relationships, source: :follower

  # user angelships
  has_many :angelships, foreign_key: "angel_id", dependent: :destroy
  has_many :dreamers, through: :angelships, source: :dreamer
  has_many :reverse_angelships, foreign_key: "dreamer_id", class_name: "Angelship", dependent: :destroy
  has_many :angels, through: :reverse_angelships, source: :angel

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,:token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,:authentication_keys => [:uid]

  before_save :ensure_authentication_token

  # Setup accessible (or protected) attributes for your model
  attr_accessible :uid, :password, :password_confirmation, :avatar, :email, :authentication_token

  # follow method
  def following?(other_user)
  	relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
  	relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
  	relationships.find_by_followed_id(other_user.id).destroy
  end

  # angel method
  def angel?(other_user)
    angelships.find_by_angel_id(other_user.id)
  end

  def dreamer?(other_user)
    angelships.find_by_dreamer_id(other_user.id)
  end

  def angel!(other_user)
    angelships.create!(dreamer_id: other_user.id)
  end

  def unangel!(other_user)
    angelships.find_by_dreamer_id(other_user.id).destroy
  end

  protected
    def email_required?
      false
    end

    def password_required? 
      false 
    end 
end

app/controllers/angelships_controller.rb
class AngelshipsController < ApplicationController
	skip_before_filter :verify_authenticity_token
	before_filter :authenticate_user!
	respond_to :json

	def create
		@user = User.find(params[:angelship][:dreamer_id])
		current_user.angel!(@user)
		@goals = @user.goals
		redirect_to status: 200
	end

	def destroy
		@user = Angelship.find(params[:id]).dreamer
		current_user.unangel!(@user)
		redirect_to status: 200
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
	skip_before_filter :verify_authenticity_token
	respond_to :html, :json
	belongs_to :goal_post

	def create
		@comment = current_user.comments.build(params[:comment])
		@comment.goal_post_id = params[:goal_post_id]
		create!{ collection_url }
	end

	# protected
	# 	def begin_of_association_chain
	# 		current_user
	# 	end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	skip_before_filter :verify_authenticity_token
	def index
		@users = friends(uids)	
	end

	protected

	def friends(uids)
		@users = []
		uids.each do |uid|
			@user = User.find_by_uid(uid)
			if @user
				@users << @user
			end
		end
	end
end

app/controllers/goal_posts_controller.rb
class GoalPostsController < InheritedResources::Base
	skip_before_filter :verify_authenticity_token
	respond_to :html, :json
	belongs_to :goal
	before_filter :authenticate_user!

	def create
		@goal_post = current_user.goal_posts.build(params[:goal_post])
		@goal_post.goal_id = params[:goal_id]
		create!{collection_url}
	end

	def new
		@goal_post = GoalPost.new
		@goal_post.pictures.build
		new!
	end

	def posts
		@users = current_user.followed_users | current_user.dreamers
		@posts = []
		@users.each do |user|
			@posts = @posts + user.goal_posts
		end
		@posts.sort!{|x,y| y.updated_at <=> x.updated_at}
	end

	def friendsgoals
		@users = friends(params[:uids])
	end

	protected

	def friends(uids)
		@users = []
		uids.each do |uid|
			@user = User.find_by_uid(uid)
			if @user
				@users << @user
			end
		end
		return @users
	end	
end

app/controllers/goals_controller.rb
class GoalsController < InheritedResources::Base
	skip_before_filter :verify_authenticity_token
	before_filter :authenticate_user!
	respond_to :html, :json

	def create
		@goal = current_user.goals.create!(params[:goal])
		create!{collection_url}
	end

	def me
		@user = current_user
	end
end

app/controllers/pictures_controller.rb
class PicturesController < InheritedResources::Base
	before_filter :load_imageable
	belongs_to :goal, :post, polymorphic: true

	def create
		# create! { store_path(@imageable.store_id)}
		create! { parent_url }
	end

	private
	def load_imageable
		resource, id = request.path.split('/')[1,2]
		@imageable = resource.singularize.classify.constantize.find(id)		
	end
end

app/controllers/relationships_controller.rb
class	RelationshipsController < ApplicationController
	skip_before_filter :verify_authenticity_token
	before_filter :authenticate_user!
	respond_to :json

	def create
		@user = User.find(params[:relationship][:followed_id])
		current_user.follow!(@user)
		redirect_to status: 200
	end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to status: 200
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	skip_before_filter :verify_authenticity_token
	def create
    respond_to do |format|
      format.html { super }
 
      format.json {
        warden.authenticate!(:scope => params[:uid], :recall => "#{controller_path}#new")
        render :status => 200, :json => { :session => { :error => "Success", :auth_token => current_user.authentication_token } }
      }
    end
  end
 
  def destroy
    respond_to do |format|
      format.html { super }
 
      format.json {
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
        current_user.authentication_token = nil
        render :json => {}.to_json, :status => :ok
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/goal_posts_helper.rb
module GoalPostsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_form.html.slim
= form_for [@goal_post,@comment] do |f|
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :goal_post
    = f.text_field :goal_post
  .actions = f.submit 'Save'

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  tr
    th Content
    th Goal post
    th
    th
    th

  - @comments.each do |comment|
    tr
      td = comment.content
      td = comment.goal_post.id
      td = link_to 'Show', resource_url(comment)
      td = link_to 'Edit', edit_resource_url(comment)
      td = link_to 'Destroy', resource_path(comment), :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Comment', new_resource_url

app/views/comments/new.html.slim
h1 New comment

= form_for [@goal_post,@comment] do |f|
  .field
    = f.label :content
    = f.text_field :content

  .actions = f.submit 'Save'

/ # = link_to 'Back', goal_goal_post_comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong Content:
  = @comment.content
p
  strong Goal post:
  = @comment.goal_post

= link_to 'Edit', edit_resource_url(@comment)
'|
= link_to 'Back', comments_path

app/views/goal_posts/edit.html.slim
h1 Editing goal_post

== render 'form'

= link_to 'Show', @goal_post
'|
= link_to 'Back', goal_posts_path

app/views/goal_posts/index.html.slim
h1 Listing goal_posts

table
  tr
    th Summary
    th Tgoal
    th Goal
    th
    th
    th

  - @goal_posts.each do |goal_post|
    tr
      td = goal_post.summary
      td = goal_post.tgoal
      td = goal_post.goal.id
      td = link_to 'Show', resource_url(goal_post)
      td = link_to 'Edit', edit_resource_url(goal_post)
      td = link_to 'Destroy', resource_path(goal_post), :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Goal post', new_resource_url

app/views/goal_posts/new.html.slim
h1 New goal_post


= form_for [@goal, @goal_post] do |f|
  .field
    = f.label :summary
    = f.text_field :summary
  .field
    = f.label :tgoal
    = f.text_field :tgoal
  .field
  	= f.fields_for :pictures do |picture|
  		.fieldset
  			= picture.file_field :image
  			
  .actions = f.submit 'Save'

= link_to 'Back', goal_goal_posts_path

app/views/goal_posts/show.html.slim
p#notice = notice

p
  strong Summary:
  = @goal_post.summary
p
  strong Tgoal:
  = @goal_post.tgoal
p
  strong Goal:
  = @goal_post.goal.name
p
  strong Image:
  - @goal_post.pictures.each do |picture|
    = image_tag picture.image_url(:thumb)
br
br
= link_to '코멘트 달기', goal_post_comments_path(@goal_post)
br
br
= link_to 'Edit', edit_resource_url(@goal_post)
'|
= link_to 'Back', goal_goal_posts_path

app/views/goals/_form.html.slim
= form_for @goal do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :statement
    = f.text_area :statement
  .field
    = f.label :startdate
    = f.date_select :startdate
  .field
    = f.label :enddate
    = f.date_select :enddate
  .actions = f.submit 'Save'

app/views/goals/edit.html.slim
h1 Editing goal

== render 'form'

= link_to 'Show', @goal
'|
= link_to 'Back', goals_path

app/views/goals/index.html.slim
h1 Listing goals

table
  tr
    th Name
    th Statement
    th Startdate
    th Enddate
    th
    th
    th

  - @goals.each do |goal|
    tr
      td = goal.name
      td = goal.statement
      td = goal.startdate
      td = goal.enddate
      td = link_to 'Show', goal
      td = link_to 'Edit', edit_goal_path(goal)
      td = link_to 'Destroy', goal, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Goal', new_goal_path

app/views/goals/new.html.slim
h1 New goal

== render 'form'

= link_to 'Back', goals_path

app/views/goals/show.html.slim
p#notice = notice

p
  strong Name:
  = @goal.name
p
  strong Statement:
  = @goal.statement
p
  strong Startdate:
  = @goal.startdate
p
  strong Enddate:
  = @goal.enddate
p
 	strong User:
 	= @goal.user.id
br
br
br
= link_to '인증샷올리기', goal_goal_posts_path(@goal)
br
br

= link_to 'Edit', edit_goal_path(@goal)
'|
= link_to 'Back', goals_path

app/views/pictures/_form.html.slim
= form_for @picture do |f|
  - if @picture.errors.any?
    #error_explanation
      h2 = "#{pluralize(@picture.errors.count, "error")} prohibited this picture from being saved:"
      ul
        - @picture.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :imageable_type
    = f.text_field :imageable_type
  .actions = f.submit 'Save'

app/views/pictures/edit.html.slim
h1 Editing picture

== render 'form'

= link_to 'Show', @picture
'|
= link_to 'Back', pictures_path

app/views/pictures/index.html.slim
h1 Listing pictures

table
  tr
    th Image
    th Imageable type
    th
    th
    th

  - @pictures.each do |picture|
    tr
      td = picture.image
      td = picture.imageable_type
      td = link_to 'Show', picture
      td = link_to 'Edit', edit_picture_path(picture)
      td = link_to 'Destroy', picture, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Picture', new_picture_path

app/views/pictures/new.html.slim
h1 New picture

== render 'form'

= link_to 'Back', pictures_path

app/views/pictures/show.html.slim
p#notice = notice

p
  strong Image:
  = @picture.image
p
  strong Imageable type:
  = @picture.imageable_type

= link_to 'Edit', edit_picture_path(@picture)
'|
= link_to 'Back', pictures_path